/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/users/guest/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Guest Session */
        post: operations["create_guest_session_v1_users_guest_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/google/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In With Google */
        post: operations["sign_in_with_google_v1_users_google_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Session */
        post: operations["refresh_session_v1_users_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_users_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/link/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Google Account */
        post: operations["link_google_account_v1_users_link_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_users_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_v1_users_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entitlements */
        get: operations["get_entitlements_v1_entitlements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/study-inputs/source-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Source Image */
        post: operations["upload_source_image_v1_study_inputs_source_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/study-inputs/source-images/{source_image_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Image */
        get: operations["get_source_image_v1_study_inputs_source_images__source_image_ref__get"];
        put?: never;
        post?: never;
        /** Delete Unattached Source Image */
        delete: operations["delete_unattached_source_image_v1_study_inputs_source_images__source_image_ref__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/study-inputs/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Study Input */
        post: operations["extract_study_input_v1_study_inputs_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/study-inputs/extract/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Extract Job */
        post: operations["create_extract_job_v1_study_inputs_extract_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/study-inputs/extract/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Extract Job */
        get: operations["get_extract_job_v1_study_inputs_extract_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/study-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Study Input */
        post: operations["create_study_input_v1_study_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/study-inputs/{study_input_id}/redact-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redact Study Input Source */
        post: operations["redact_study_input_source_v1_study_inputs__study_input_id__redact_source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/questions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Questions */
        post: operations["generate_questions_v1_questions_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/questions/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Question Generation Job */
        post: operations["create_question_generation_job_v1_questions_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/questions/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Question Generation Job */
        get: operations["get_question_generation_job_v1_questions_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/tonight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tonight Question */
        get: operations["get_tonight_question_v1_review_tonight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/pick-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pickable Topics */
        get: operations["get_pickable_topics_v1_review_pick_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/saved-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Saved Inputs */
        get: operations["get_saved_inputs_v1_review_saved_inputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/from-topic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Question From Topic */
        post: operations["get_question_from_topic_v1_review_from_topic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/topic/{topic_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Saved Topic Source */
        get: operations["get_saved_topic_source_v1_review_topic__topic_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/saved-input/{study_input_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Saved Input Detail */
        get: operations["get_saved_input_detail_v1_review_saved_input__study_input_id__get"];
        put?: never;
        post?: never;
        /** Delete Saved Input */
        delete: operations["delete_saved_input_v1_review_saved_input__study_input_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/from-saved-topic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Questions From Saved Topic */
        post: operations["generate_questions_from_saved_topic_v1_review_from_saved_topic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/from-saved-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Questions From Saved Input */
        post: operations["generate_questions_from_saved_input_v1_review_from_saved_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/topic/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Topic */
        delete: operations["delete_topic_v1_review_topic__topic_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submit_answer_v1_review_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage Limits */
        get: operations["get_usage_limits_v1_usage_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/reminder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Reminder Settings */
        patch: operations["patch_reminder_settings_v1_settings_reminder_patch"];
        trace?: never;
    };
    "/v1/waitlist/signups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Waitlist Signup */
        post: operations["create_waitlist_signup_v1_waitlist_signups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ops Digest */
        get: operations["get_ops_digest_v1_ops_digest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/alert-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Ops Alerts */
        post: operations["run_ops_alerts_v1_ops_alert_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerSubmitRequest */
        AnswerSubmitRequest: {
            /** Question Id */
            question_id: string;
            /** Selected Index */
            selected_index?: number | null;
            /** Selected Text */
            selected_text?: string | null;
            /**
             * Response Time Ms
             * @default 0
             */
            response_time_ms: number;
        };
        /** AnswerSubmitResponse */
        AnswerSubmitResponse: {
            /** Is Correct */
            is_correct: boolean;
            /** Correct Index */
            correct_index: number | null;
            /** Correct Text */
            correct_text: string | null;
            /** Explanation */
            explanation: string;
            /** Current Streak */
            current_streak: number;
        };
        /** AuthSessionResponse */
        AuthSessionResponse: {
            user: components["schemas"]["UserResponse"];
            tokens: components["schemas"]["TokenPair"];
            /**
             * Is New User
             * @default false
             */
            is_new_user: boolean;
        };
        /** EntitlementsResponse */
        EntitlementsResponse: {
            /**
             * Plan
             * @enum {string}
             */
            plan: EntitlementsResponsePlan;
            /** Billing Enabled */
            billing_enabled: boolean;
        };
        /** ExtractedPointResponse */
        ExtractedPointResponse: {
            /** Text */
            text: string;
        };
        /** GenerateFromSavedInputRequest */
        GenerateFromSavedInputRequest: {
            /** Study Input Id */
            study_input_id: string;
            /** Selected Topic Ids */
            selected_topic_ids?: string[];
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** GenerateFromSavedInputResponse */
        GenerateFromSavedInputResponse: {
            /** Questions */
            questions: components["schemas"]["QuestionOutput"][];
        };
        /** GenerateFromSavedTopicRequest */
        GenerateFromSavedTopicRequest: {
            /** Topic Id */
            topic_id: string;
            /** Selected Topic Ids */
            selected_topic_ids?: string[];
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** GenerateFromSavedTopicResponse */
        GenerateFromSavedTopicResponse: {
            /** Questions */
            questions: components["schemas"]["QuestionOutput"][];
        };
        /** GoogleSignInRequest */
        GoogleSignInRequest: {
            /** Id Token */
            id_token: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Locale
             * @default en
             */
            locale: string;
            /** Device Label */
            device_label?: string | null;
        };
        /** GuestSessionRequest */
        GuestSessionRequest: {
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Locale
             * @default en
             */
            locale: string;
            /** Reminder Time */
            reminder_time?: string | null;
            /** Device Label */
            device_label?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinkGoogleRequest */
        LinkGoogleRequest: {
            /** Id Token */
            id_token: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /** PickTopicQuestionRequest */
        PickTopicQuestionRequest: {
            /** Topic Id */
            topic_id: string;
        };
        /** QuestionGenerateRequest */
        QuestionGenerateRequest: {
            /** Study Input Id */
            study_input_id: string;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** QuestionGenerateResponse */
        QuestionGenerateResponse: {
            /** Questions */
            questions: components["schemas"]["QuestionOutput"][];
        };
        /** QuestionGenerationJobResponse */
        QuestionGenerationJobResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: QuestionGenerationJobResponseStatus;
            /** Questions */
            questions?: components["schemas"]["QuestionOutput"][] | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QuestionOutput */
        QuestionOutput: {
            /** Id */
            id: string;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: QuestionOutputQuestion_type;
            /** Question Text */
            question_text: string;
            /** Choices */
            choices?: string[] | null;
            /** Answer Index */
            answer_index?: number | null;
            /** Answer Text */
            answer_text?: string | null;
            /** Explanation */
            explanation: string;
            /** Resurface Reason */
            resurface_reason?: "missed_before" | null;
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReminderSettingsPatchRequest */
        ReminderSettingsPatchRequest: {
            /**
             * Reminder Time
             * Format: time
             */
            reminder_time: string;
            /**
             * Notifications Enabled
             * @default true
             */
            notifications_enabled: boolean;
            /** Timezone */
            timezone: string;
        };
        /** ReminderSettingsResponse */
        ReminderSettingsResponse: {
            /** User Id */
            user_id: string;
            /**
             * Reminder Time
             * Format: time
             */
            reminder_time: string;
            /** Notifications Enabled */
            notifications_enabled: boolean;
            /** Timezone */
            timezone: string;
        };
        /** ReviewQuestionResponse */
        ReviewQuestionResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: ReviewQuestionResponseMode;
            question: components["schemas"]["QuestionOutput"];
        };
        /** SavedStudyInputDetailResponse */
        SavedStudyInputDetailResponse: {
            /** Study Input Id */
            study_input_id: string;
            /**
             * Input Type
             * @enum {string}
             */
            input_type: SavedStudyInputDetailResponseInput_type;
            /** Source Kind */
            source_kind?: SavedStudyInputDetailResponseSource_kindAnyOf0 | null;
            /** Source Preview Text */
            source_preview_text?: string | null;
            /** Source Image Ref */
            source_image_ref?: string | null;
            /** Topics */
            topics: components["schemas"]["TopicResponse"][];
        };
        /** SavedStudyInputSummaryResponse */
        SavedStudyInputSummaryResponse: {
            /** Study Input Id */
            study_input_id: string;
            /**
             * Input Type
             * @enum {string}
             */
            input_type: SavedStudyInputSummaryResponseInput_type;
            /** Source Kind */
            source_kind?: SavedStudyInputSummaryResponseSource_kindAnyOf0 | null;
            /** Source Preview Text */
            source_preview_text?: string | null;
            /** Source Image Ref */
            source_image_ref?: string | null;
            /** Title */
            title: string;
            /** Preview */
            preview: string;
            /** Bookmarked Count */
            bookmarked_count: number;
            /** Topic Id */
            topic_id: string;
        };
        /** SavedStudyInputsResponse */
        SavedStudyInputsResponse: {
            /** Items */
            items: components["schemas"]["SavedStudyInputSummaryResponse"][];
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Has More */
            has_more: boolean;
            /** Total Count */
            total_count: number;
        };
        /** SavedTopicSourceResponse */
        SavedTopicSourceResponse: {
            /** Topic Id */
            topic_id: string;
            /** Study Input Id */
            study_input_id: string;
            /**
             * Input Type
             * @enum {string}
             */
            input_type: SavedTopicSourceResponseInput_type;
            /** Source Kind */
            source_kind?: SavedTopicSourceResponseSource_kindAnyOf0 | null;
            /** Source Preview Text */
            source_preview_text?: string | null;
            /** Source Image Ref */
            source_image_ref?: string | null;
            /** Topics */
            topics: components["schemas"]["TopicResponse"][];
        };
        /** StatsResponse */
        StatsResponse: {
            /** Current Streak */
            current_streak: number;
            /** Total Answered */
            total_answered: number;
            /** Correct Count */
            correct_count: number;
            /** Accuracy */
            accuracy: number;
            /** Recent Wrong Topics */
            recent_wrong_topics: string[];
            /** Answered Today */
            answered_today: boolean;
            /** Answered Dates This Month */
            answered_dates_this_month: string[];
        };
        /** StudyInputCreateRequest */
        StudyInputCreateRequest: {
            /**
             * Input Type
             * @enum {string}
             */
            input_type: StudyInputCreateRequestInput_type;
            /** Content */
            content: string[] | string;
            /** Starred Indices */
            starred_indices?: number[];
            /** Source Kind */
            source_kind?: StudyInputCreateRequestSource_kindAnyOf0 | null;
            /** Source Preview Text */
            source_preview_text?: string | null;
            /** Source Image Ref */
            source_image_ref?: string | null;
        };
        /** StudyInputCreateResponse */
        StudyInputCreateResponse: {
            /** Study Input Id */
            study_input_id: string;
            /** Topics */
            topics: components["schemas"]["TopicResponse"][];
            /** Source Kind */
            source_kind?: StudyInputCreateResponseSource_kindAnyOf0 | null;
            /** Source Preview Text */
            source_preview_text?: string | null;
            /** Source Image Ref */
            source_image_ref?: string | null;
        };
        /** StudyInputExtractJobResponse */
        StudyInputExtractJobResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: StudyInputExtractJobResponseStatus;
            /** Source Preview */
            source_preview?: string | null;
            /** Points */
            points?: components["schemas"]["ExtractedPointResponse"][] | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StudyInputExtractRequest */
        StudyInputExtractRequest: {
            /**
             * Source Type
             * @enum {string}
             */
            source_type: StudyInputExtractRequestSource_type;
            /** Source Text */
            source_text?: string | null;
            /** Image Base64 */
            image_base64?: string | null;
            /** Image Mime Type */
            image_mime_type?: string | null;
        };
        /** StudyInputExtractResponse */
        StudyInputExtractResponse: {
            /** Source Preview */
            source_preview: string;
            /** Points */
            points: components["schemas"]["ExtractedPointResponse"][];
        };
        /** StudyInputSourceImageUploadRequest */
        StudyInputSourceImageUploadRequest: {
            /** Image Base64 */
            image_base64: string;
            /**
             * Image Mime Type
             * @default image/jpeg
             */
            image_mime_type: string;
        };
        /** StudyInputSourceImageUploadResponse */
        StudyInputSourceImageUploadResponse: {
            /** Source Image Ref */
            source_image_ref: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TonightTopicsResponse */
        TonightTopicsResponse: {
            /** Topics */
            topics: components["schemas"]["TopicResponse"][];
        };
        /** TopicResponse */
        TopicResponse: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Is Starred */
            is_starred: boolean;
        };
        /** UsageLimitInfo */
        UsageLimitInfo: {
            /** Limit */
            limit: number;
            /** Used */
            used: number;
            /** Remaining */
            remaining: number;
        };
        /** UsageLimitsResponse */
        UsageLimitsResponse: {
            photo_extract_daily: components["schemas"]["UsageLimitInfo"];
            question_generation_daily: components["schemas"]["UsageLimitInfo"];
            question_generation_monthly: components["schemas"]["UsageLimitInfo"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Auth Provider */
            auth_provider: string;
            /** Email Nullable */
            email_nullable: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Timezone */
            timezone: string;
            /** Locale */
            locale: string;
            /** Reminder Time */
            reminder_time: string | null;
            /** Notifications Enabled */
            notifications_enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaitlistSignupCreateRequest */
        WaitlistSignupCreateRequest: {
            /** Email */
            email: string;
            /**
             * Source
             * @default landing-page
             */
            source: string | null;
        };
        /** WaitlistSignupResponse */
        WaitlistSignupResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Source Nullable */
            source_nullable: string | null;
            /** Signup Count */
            signup_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Last Signup At
             * Format: date-time
             */
            last_signup_at: string;
            /** Created New */
            created_new: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_guest_session_v1_users_guest_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_with_google_v1_users_google_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_session_v1_users_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_users_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_google_account_v1_users_link_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkGoogleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    delete_me_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entitlements_v1_entitlements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementsResponse"];
                };
            };
        };
    };
    upload_source_image_v1_study_inputs_source_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyInputSourceImageUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyInputSourceImageUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_image_v1_study_inputs_source_images__source_image_ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_image_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_unattached_source_image_v1_study_inputs_source_images__source_image_ref__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_image_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_study_input_v1_study_inputs_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyInputExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyInputExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_extract_job_v1_study_inputs_extract_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyInputExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyInputExtractJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extract_job_v1_study_inputs_extract_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyInputExtractJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_study_input_v1_study_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyInputCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyInputCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redact_study_input_source_v1_study_inputs__study_input_id__redact_source_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_input_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_questions_v1_questions_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_generation_job_v1_questions_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionGenerationJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_question_generation_job_v1_questions_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionGenerationJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tonight_question_v1_review_tonight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQuestionResponse"];
                };
            };
        };
    };
    get_pickable_topics_v1_review_pick_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TonightTopicsResponse"];
                };
            };
        };
    };
    get_saved_inputs_v1_review_saved_inputs_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedStudyInputsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_question_from_topic_v1_review_from_topic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickTopicQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saved_topic_source_v1_review_topic__topic_id__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedTopicSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_saved_input_detail_v1_review_saved_input__study_input_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_input_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedStudyInputDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_saved_input_v1_review_saved_input__study_input_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_input_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_questions_from_saved_topic_v1_review_from_saved_topic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateFromSavedTopicRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateFromSavedTopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_questions_from_saved_input_v1_review_from_saved_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateFromSavedInputRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateFromSavedInputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topic_v1_review_topic__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_v1_review_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    get_usage_limits_v1_usage_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageLimitsResponse"];
                };
            };
        };
    };
    patch_reminder_settings_v1_settings_reminder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderSettingsPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_waitlist_signup_v1_waitlist_signups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistSignupCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistSignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ops_digest_v1_ops_digest_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ops-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ops_alerts_v1_ops_alert_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ops-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
export enum EntitlementsResponsePlan {
    free = "free",
    plus = "plus"
}
export enum QuestionGenerationJobResponseStatus {
    queued = "queued",
    running = "running",
    succeeded = "succeeded",
    failed = "failed"
}
export enum QuestionOutputQuestion_type {
    mcq = "mcq",
    true_false = "true_false",
    fill_blank = "fill_blank"
}
export enum ReviewQuestionResponseMode {
    auto = "auto",
    picked = "picked"
}
export enum SavedStudyInputDetailResponseInput_type {
    keywords = "keywords",
    notes = "notes"
}
export enum SavedStudyInputDetailResponseSource_kindAnyOf0 {
    photo = "photo",
    manual = "manual"
}
export enum SavedStudyInputSummaryResponseInput_type {
    keywords = "keywords",
    notes = "notes"
}
export enum SavedStudyInputSummaryResponseSource_kindAnyOf0 {
    photo = "photo",
    manual = "manual"
}
export enum SavedTopicSourceResponseInput_type {
    keywords = "keywords",
    notes = "notes"
}
export enum SavedTopicSourceResponseSource_kindAnyOf0 {
    photo = "photo",
    manual = "manual"
}
export enum StudyInputCreateRequestInput_type {
    keywords = "keywords",
    notes = "notes"
}
export enum StudyInputCreateRequestSource_kindAnyOf0 {
    photo = "photo",
    manual = "manual"
}
export enum StudyInputCreateResponseSource_kindAnyOf0 {
    photo = "photo",
    manual = "manual"
}
export enum StudyInputExtractJobResponseStatus {
    queued = "queued",
    running = "running",
    succeeded = "succeeded",
    failed = "failed"
}
export enum StudyInputExtractRequestSource_type {
    text = "text",
    image = "image"
}
